import { 
  Shield, Target, Swords, Trophy, Users, Zap, 
  ChevronRight, Menu, X, Search, Star, 
  TrendingUp, BarChart3, Gamepad2, Crosshair,
  Flame, Award, Medal, Skull, Bomb,
  Mail, Phone, MapPin, Clock, Send,
  CheckCircle, AlertCircle, Info, HelpCircle,
  Facebook, Twitter, Instagram, Youtube, Github,
  ShoppingCart, CreditCard, Palette, Sparkles,
  ChevronLeft, ArrowRight, Move, CornerDownLeft,
  Check, Plus, Edit, Trash, Copy, Share, Download,
  MessageSquare, Bot, Home, Settings, User, Bell,
  Lock, Unlock, Key, LogIn, LogOut, RefreshCw,
  Heart, ThumbsUp, MessageCircle, Eye, EyeOff,
  Filter, Grid, List, LayoutGrid, Maximize2,
  Minimize2, ExternalLink, Link, Paperclip,
  Calendar, Clock3, Timer, History, Activity,
  Globe, Server, Database, Wifi, WifiOff,
  Volume2, VolumeX, Play, Pause, SkipForward,
  Folder, FileText, Image as ImageIcon, Video,
  Music, Mic, MicOff, Camera, CameraOff,
  Sun, Moon, Monitor, Smartphone, Tablet,
  Battery, BatteryCharging, BatteryLow,
  Bluetooth, Cast, Airplay, Radio, Tv,
  Car, Plane, Train, Bus, Bike, Footprints,
  Coffee, Pizza, Beer, Cake, IceCream,
  ShoppingBag, Store, Tag, Percent, Gift,
  Bookmark, Flag, Map, Navigation, Compass,
  Anchor, Ship, Truck, Package, Box,
  Wrench, Tool, Hammer, Scissors, Ruler,
  Paintbrush, PenTool, Type, AlignLeft,
  Bold, Italic, Underline, Strikethrough,
  Code, Terminal, Command, Hash, AtSign,
  DollarSign, Euro, PoundSterling, Bitcoin,
  Cloud, CloudRain, CloudSnow, SunDim, Wind,
  Thermometer, Droplets, Umbrella, Snowflake,
  FlameKindling, ZapOff, Plug, BatteryMedium,
  Headphones, Speaker, Volume1, Volume,
  CastConnected, MonitorSpeaker, Projector,
  Watch, AlarmClock, Stopwatch, Hourglass,
  CalendarDays, CalendarCheck, CalendarX,
  Inbox, MailOpen, SendHorizontal, Reply,
  ReplyAll, Forward, Trash2, Archive,
  AlertTriangle, AlertOctagon, ShieldAlert,
  ShieldCheck, ShieldX, ShieldQuestion,
  LockClosed, LockOpen, KeyRound, Fingerprint,
  ScanFace, ScanLine, Scan, QrCode,
  SmartphoneNfc, CreditCardIcon, Wallet,
  Receipt, FileInvoice, Calculator, PiggyBank,
  Landmark, Building2, Building, Factory,
  Warehouse, StoreIcon, Hotel, BedDouble,
  Bath, Sofa, Lamp, Fan, AirVent,
  ThermometerSun, ThermometerSnowflake,
  Droplet, Waves, DropletOff, SprayCan,
  PaintBucket, Brush, Eraser, Pen,
  Highlighter, Pencil, PencilLine,
  StickyNote, Clipboard, ClipboardCheck,
  ClipboardX, ClipboardList, File,
  FilePlus, FileMinus, FileX, FileCheck,
  FileQuestion, FileWarning, FileCode,
  FileJson, FileType, FileImage, FileVideo,
  FileAudio, FileArchive, FileUp, FileDown,
  FolderPlus, FolderMinus, FolderOpen,
  FolderTree, Folders, FolderX, FolderCheck,
  FolderSearch, FolderSymlink, FolderHeart,
  FolderCog, FolderKey, FolderLock,
  Images, ImagePlus, ImageMinus, ImageOff,
  GalleryVertical, GalleryHorizontal,
  GalleryThumbnails, GalleryVerticalEnd,
  ImagesIcon, PictureInPicture, Film,
  Clapperboard, VideoOff, Webcam, WebcamOff,
  Mic2, Headset, HeadphonesIcon, SpeakerIcon,
  SpeakerOff, VolumeIcon, VolumeXIcon,
  Volume1Icon, Volume2Icon, CastIcon,
  AirplayIcon, MonitorPlay, MonitorX,
  SmartphoneIcon, TabletIcon, Laptop,
  Computer, TvIcon, RadioIcon, RadioTower,
  Antenna, Satellite, Radar, Signal,
  SignalHigh, SignalMedium, SignalLow,
  SignalZero, WifiIcon, WifiOffIcon,
  WifiHigh, WifiLow, Ethernet, Router,
  ServerIcon, ServerOff, ServerCrash,
  DatabaseIcon, DatabaseBackup, HardDrive,
  HardDriveDownload, HardDriveUpload,
  Disc, Disc2, Disc3, Album, FileMusic,
  FileDigit, Binary, Hexagon, Pentagon,
  Octagon, Square, Circle, Triangle,
  Diamond, HexagonIcon, OctagonIcon,
  StarIcon, HeartIcon, ThumbsUpIcon,
  ThumbsDown, Smile, Frown, Meh, Laugh,
  Annoyed, Angry, FrownIcon, SmileIcon,
  LaughIcon, MehIcon, AnnoyedIcon, AngryIcon,
  UserIcon, UserPlus, UserMinus, UserX,
  UsersIcon, UserCheck, UserCog, UserCircle,
  UserRound, UsersRound, UserRoundPlus,
  UserRoundMinus, UserRoundX, UserRoundCheck,
  UserRoundCog, UserRoundCircle,
  Contact, Contact2, IdCard, Vcard,
  FingerprintIcon, ScanFaceIcon, ScanLineIcon,
  ScanIcon, QrCodeIcon, Barcode,
  CreditCardIconIcon, WalletIcon, ReceiptIcon,
  Banknote, Coins, BanknoteIcon, PiggyBankIcon,
  LandmarkIcon, Building2Icon, BuildingIcon,
  FactoryIcon, WarehouseIcon, StoreIconIcon,
  HotelIcon, BedDoubleIcon, BathIcon,
  SofaIcon, LampIcon, FanIcon, AirVentIcon,
  ThermometerSunIcon, ThermometerSnowflakeIcon,
  DropletIcon, WavesIcon, DropletOffIcon,
  SprayCanIcon, PaintBucketIcon, BrushIcon,
  EraserIcon, PenIcon, HighlighterIcon,
  PencilIcon, PencilLineIcon, StickyNoteIcon,
  ClipboardIcon, ClipboardCheckIcon,
  ClipboardXIcon, ClipboardListIcon, FileIcon,
  FilePlusIcon, FileMinusIcon, FileXIcon,
  FileCheckIcon, FileQuestionIcon,
  FileWarningIcon, FileCodeIcon, FileJsonIcon,
  FileTypeIcon, FileImageIcon, FileVideoIcon,
  FileAudioIcon, FileArchiveIcon, FileUpIcon,
  FileDownIcon, FolderPlusIcon, FolderMinusIcon,
  FolderOpenIcon, FolderTreeIcon, FoldersIcon,
  FolderXIcon, FolderCheckIcon, FolderSearchIcon,
  FolderSymlinkIcon, FolderHeartIcon,
  FolderCogIcon, FolderKeyIcon, FolderLockIcon,
  ImagesIcon, ImagePlusIcon, ImageMinusIcon,
  ImageOffIcon, GalleryVerticalIcon,
  GalleryHorizontalIcon, GalleryThumbnailsIcon,
  GalleryVerticalEndIcon, ImagesIconIcon,
  PictureInPictureIcon, FilmIcon,
  ClapperboardIcon, VideoOffIcon, WebcamIcon,
  WebcamOffIcon, Mic2Icon, HeadsetIcon,
  HeadphonesIconIcon, SpeakerIconIcon,
  SpeakerOffIcon, VolumeIconIcon, VolumeXIconIcon,
  Volume1IconIcon, Volume2IconIcon, CastIconIcon,
  AirplayIconIcon, MonitorPlayIcon, MonitorXIcon,
  SmartphoneIconIcon, TabletIconIcon, LaptopIcon,
  ComputerIcon, TvIconIcon, RadioIconIcon,
  RadioTowerIcon, AntennaIcon, SatelliteIcon,
  RadarIcon, SignalIcon, SignalHighIcon,
  SignalMediumIcon, SignalLowIcon, SignalZeroIcon,
  WifiIconIcon, WifiOffIconIcon, WifiHighIcon,
  WifiLowIcon, EthernetIcon, RouterIcon,
  ServerIconIcon, ServerOffIcon, ServerCrashIcon,
  DatabaseIconIcon, DatabaseBackupIcon, HardDriveIcon,
  HardDriveDownloadIcon, HardDriveUploadIcon,
  DiscIcon, Disc2Icon, Disc3Icon, AlbumIcon,
  FileMusicIcon, FileDigitIcon, BinaryIcon,
  HexagonIconIcon, PentagonIcon, OctagonIconIcon,
  SquareIcon, CircleIcon, TriangleIcon,
  DiamondIcon, StarIconIcon, HeartIconIcon,
  ThumbsUpIconIcon, ThumbsDownIcon, SmileIconIcon,
  FrownIconIcon, MehIconIcon, LaughIconIcon,
  AnnoyedIconIcon, AngryIconIcon, Rocket,
  PlaneIcon, PlaneTakeoff, PlaneLanding,
  CompassIcon, NavigationIcon, MapIcon,
  MapPinIcon, MapPinned, Navigation2,
  Navigation2Off, Locate, LocateFixed,
  LocateOff, RadarIconIcon, TargetIcon,
  CrosshairIcon, Focus, Aperture, ScanEye,
  EyeIcon, EyeOffIcon, Glasses, Sunglasses,
  ContactIcon, Contact2Icon, IdCardIcon,
  VcardIcon
} from 'lucide-react'

const iconMap = {
  shield: Shield,
  target: Target,
  swords: Swords,
  trophy: Trophy,
  users: Users,
  zap: Zap,
  'chevron-right': ChevronRight,
  menu: Menu,
  x: X,
  search: Search,
  star: Star,
  'trending-up': TrendingUp,
  'bar-chart': BarChart3,
  gamepad: Gamepad2,
  crosshair: Crosshair,
  flame: Flame,
  award: Award,
  medal: Medal,
  skull: Skull,
  bomb: Bomb,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  clock: Clock,
  send: Send,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  github: Github,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  palette: Palette,
  sparkles: Sparkles,
  'chevron-left': ChevronLeft,
  'arrow-right': ArrowRight,
  move: Move,
  'corner-down-left': CornerDownLeft,
  check: Check,
  plus: Plus,
  edit: Edit,
  trash: Trash,
  copy: Copy,
  share: Share,
  download: Download,
  'message-square': MessageSquare,
  bot: Bot,
  home: Home,
  settings: Settings,
  user: User,
  bell: Bell,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  'log-in': LogIn,
  'log-out': LogOut,
  'refresh-cw': RefreshCw,
  heart: Heart,
  'thumbs-up': ThumbsUp,
  'message-circle': MessageCircle,
  eye: Eye,
  'eye-off': EyeOff,
  filter: Filter,
  grid: Grid,
  list: List,
  'layout-grid': LayoutGrid,
  maximize: Maximize2,
  minimize: Minimize2,
  'external-link': ExternalLink,
  link: Link,
  paperclip: Paperclip,
  calendar: Calendar,
  'clock-3': Clock3,
  timer: Timer,
  history: History,
  activity: Activity,
  globe: Globe,
  server: Server,
  database: Database,
  wifi: Wifi,
  'wifi-off': WifiOff,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  play: Play,
  pause: Pause,
  'skip-forward': SkipForward,
  folder: Folder,
  'file-text': FileText,
  image: ImageIcon,
  video: Video,
  music: Music,
  mic: Mic,
  'mic-off': MicOff,
  camera: Camera,
  'camera-off': CameraOff,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  battery: Battery,
  'battery-charging': BatteryCharging,
  bluetooth: Bluetooth,
  cast: Cast,
  airplay: Airplay,
  radio: Radio,
  tv: Tv,
  car: Car,
  plane: Plane,
  train: Train,
  bus: Bus,
  bike: Bike,
  footprints: Footprints,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  cake: Cake,
  'ice-cream': IceCream,
  'shopping-bag': ShoppingBag,
  store: Store,
  tag: Tag,
  percent: Percent,
  gift: Gift,
  bookmark: Bookmark,
  flag: Flag,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  anchor: Anchor,
  ship: Ship,
  truck: Truck,
  package: Package,
  box: Box,
  wrench: Wrench,
  tool: Tool,
  hammer: Hammer,
  scissors: Scissors,
  ruler: Ruler,
  paintbrush: Paintbrush,
  'pen-tool': PenTool,
  type: Type,
  'align-left': AlignLeft,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  code: Code,
  terminal: Terminal,
  command: Command,
  hash: Hash,
  'at-sign': AtSign,
  'dollar-sign': DollarSign,
  euro: Euro,
  'pound-sterling': PoundSterling,
  bitcoin: Bitcoin,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'sun-dim': SunDim,
  wind: Wind,
  thermometer: Thermometer,
  droplets: Droplets,
  umbrella: Umbrella,
  snowflake: Snowflake,
  rocket: Rocket,
  'bar-chart-3': BarChart3,
  'trending-up': TrendingUp,
  'trending-down': TrendingUp,
  activity: Activity,
  'pie-chart': BarChart3,
  'line-chart': TrendingUp
}

function SafeIcon({ name, size = 24, className = '', color }) {
  const IconComponent = iconMap[name] || HelpCircle
  
  return (
    <IconComponent 
      size={size} 
      className={className} 
      color={color}
    />
  )
}

export default SafeIcon